name: Test

on:
  push:
    branches: [main]
  pull_request:

permissions: read-all

jobs:
  test:
    name: Test [Node ${{ matrix.node-version }}]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 22]
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: "Commit Lint"
        run: npm run
      - name: Build
        run: npm run build
        if: success() || failure()
      - name: "Test: ESM"
        run: npm run test:esm
      - name: "Test: Features"
        run: npm run test:features
        if: success() || failure()
      - name: "Test: QUnit"
        run: npm run test:qunit
        if: success() || failure()
      - name: "Test: No:Specs"
        run: npm run test:no:specs
        if: success() || failure()
      - name: "Test: CJS"
        run: npm run test:cjs
        if: success() || failure()
      - name: "Lint"
        run: npm run lint:ci
        if: success() || failure()
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: eslint.sarif
        if: success() || failure()
